### PR TITLE
Remove unused images

### PR DESCRIPTION
**Pull request by miguelpduarte**
The files are now stored on the server only, and not in version control.
Also updated .gitignore to reflect the path change in #191

### CODE REVIEW

**Review by SocksDevil — COMMENTED** [review]
This PR is good to go, but we'll wait until the dockerization has been properly tested to merge it

**Comment by imnotteixeira** [comment]
After #199 and #192, this should be good to go @andrefmrocha

**Comment by miguelpduarte** [comment]
@imnotteixeira just to clarify, this isn't even related to those PRs. These images were being unused and were leftover from the old website which had the images in the repo instead of local storage / CDN.

So this could've been merged beforehand with no difference whatsoever

**Comment by imnotteixeira** [comment]
@miguelpduarte I agree, I was just referring to the previous comment, that mentioned that.

**Review by SocksDevil — APPROVED** [review]
This could have been merged long ago but got lost, cheers @imnotteixeira , :rocket:

**Pull request merged**
